# Generated by Django 2.2.5 on 2019-09-19 16:01

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190918_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='introduce',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
    ]
